<template>
  <div class="basic-menu-container">
    <BasicMenu
      :permissionMenu="permissionMenu"
      :showMessageList="showMessageList"
    ></BasicMenu>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { BasicMenu } from '../../components/BasicLayout';
/** props */

/** emits */

/** state */
const permissionMenu = ref([
  {
    moduleNameCn: '首页',
    moduleNameEn: 'Home',
    moduleId: 0,
    nodes: [
      {
        moduleId: 761,
        moduleNameCn: '首页',
        moduleNameEn: 'Home',
        moduleParentId: 0,
        nodes: [],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-shouye1',
        moduleUrl: '/homePageTrade',
      },
      {
        moduleId: 674,
        moduleNameCn: 'OPASST',
        moduleNameEn: 'OPASST',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 675,
            moduleNameCn: 'OPASST',
            moduleNameEn: 'OPASST',
            moduleParentId: 674,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/opasst/account',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-opasst',
      },
      {
        moduleId: 796,
        moduleNameCn: 'OPCCOUNT',
        moduleNameEn: 'OPCCOUNT',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 803,
            moduleNameCn: 'OPCCOUNT报表',
            moduleNameEn: 'Opccount Statement',
            moduleParentId: 796,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/opccount/reportForms',
          },
          {
            moduleId: 802,
            moduleNameCn: '代付账户管理',
            moduleNameEn: 'POBO Account',
            moduleParentId: 796,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/opccount/fundPaymentAccountManage',
          },
          {
            moduleId: 801,
            moduleNameCn: '提现账户管理',
            moduleNameEn: 'Withdrawal Account',
            moduleParentId: 796,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/opccount/withdrawalAccountManage',
          },
          {
            moduleId: 800,
            moduleNameCn: '代付申请',
            moduleNameEn: 'POBO Application',
            moduleParentId: 796,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/opccount/fundPayment',
          },
          {
            moduleId: 799,
            moduleNameCn: '自动提现',
            moduleNameEn: 'Automatic withdrawal',
            moduleParentId: 796,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/opccount/automaticWithdrawal',
          },
          {
            moduleId: 798,
            moduleNameCn: '提现申请',
            moduleNameEn: 'Withdrawal Application',
            moduleParentId: 796,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/opccount/withdrawNorate',
          },
          {
            moduleId: 797,
            moduleNameCn: '首页',
            moduleNameEn: 'Home',
            moduleParentId: 796,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/opccount',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-opccount',
      },
    ],
    routerUrl: '/homePageTrade',
    treeNodeList: [
      {
        moduleId: 761,
        moduleNameCn: '首页',
        moduleNameEn: 'Home',
        moduleParentId: 0,
        nodes: [],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-shouye1',
        moduleUrl: '/homePageTrade',
        moduleIconName: 'icon-shouye1',
        routerUrl: '/homePageTrade',
        treeNodeList: [],
      },
      {
        moduleId: 674,
        moduleNameCn: 'OPASST',
        moduleNameEn: 'OPASST',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 675,
            moduleNameCn: 'OPASST',
            moduleNameEn: 'OPASST',
            moduleParentId: 674,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/opasst/account',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-opasst',
        moduleIconName: 'icon-opasst',
        routerUrl: '/opasst/account',
        treeNodeList: [
          {
            moduleId: 675,
            moduleNameCn: 'OPASST',
            moduleNameEn: 'OPASST',
            moduleParentId: 674,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/opasst/account',
            routerUrl: '/opasst/account',
            treeNodeList: [],
          },
        ],
      },
      {
        moduleId: 796,
        moduleNameCn: 'OPCCOUNT',
        moduleNameEn: 'OPCCOUNT',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 803,
            moduleNameCn: 'OPCCOUNT报表',
            moduleNameEn: 'Opccount Statement',
            moduleParentId: 796,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/opccount/reportForms',
          },
          {
            moduleId: 802,
            moduleNameCn: '代付账户管理',
            moduleNameEn: 'POBO Account',
            moduleParentId: 796,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/opccount/fundPaymentAccountManage',
          },
          {
            moduleId: 801,
            moduleNameCn: '提现账户管理',
            moduleNameEn: 'Withdrawal Account',
            moduleParentId: 796,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/opccount/withdrawalAccountManage',
          },
          {
            moduleId: 800,
            moduleNameCn: '代付申请',
            moduleNameEn: 'POBO Application',
            moduleParentId: 796,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/opccount/fundPayment',
          },
          {
            moduleId: 799,
            moduleNameCn: '自动提现',
            moduleNameEn: 'Automatic withdrawal',
            moduleParentId: 796,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/opccount/automaticWithdrawal',
          },
          {
            moduleId: 798,
            moduleNameCn: '提现申请',
            moduleNameEn: 'Withdrawal Application',
            moduleParentId: 796,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/opccount/withdrawNorate',
          },
          {
            moduleId: 797,
            moduleNameCn: '首页',
            moduleNameEn: 'Home',
            moduleParentId: 796,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/opccount',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-opccount',
        moduleIconName: 'icon-opccount',
        routerUrl: '/opccount/reportForms',
        treeNodeList: [
          {
            moduleId: 803,
            moduleNameCn: 'OPCCOUNT报表',
            moduleNameEn: 'Opccount Statement',
            moduleParentId: 796,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/opccount/reportForms',
            routerUrl: '/opccount/reportForms',
            treeNodeList: [],
          },
          {
            moduleId: 802,
            moduleNameCn: '代付账户管理',
            moduleNameEn: 'POBO Account',
            moduleParentId: 796,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/opccount/fundPaymentAccountManage',
            routerUrl: '/opccount/fundPaymentAccountManage',
            treeNodeList: [],
          },
          {
            moduleId: 801,
            moduleNameCn: '提现账户管理',
            moduleNameEn: 'Withdrawal Account',
            moduleParentId: 796,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/opccount/withdrawalAccountManage',
            routerUrl: '/opccount/withdrawalAccountManage',
            treeNodeList: [],
          },
          {
            moduleId: 800,
            moduleNameCn: '代付申请',
            moduleNameEn: 'POBO Application',
            moduleParentId: 796,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/opccount/fundPayment',
            routerUrl: '/opccount/fundPayment',
            treeNodeList: [],
          },
          {
            moduleId: 799,
            moduleNameCn: '自动提现',
            moduleNameEn: 'Automatic withdrawal',
            moduleParentId: 796,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/opccount/automaticWithdrawal',
            routerUrl: '/opccount/automaticWithdrawal',
            treeNodeList: [],
          },
          {
            moduleId: 798,
            moduleNameCn: '提现申请',
            moduleNameEn: 'Withdrawal Application',
            moduleParentId: 796,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/opccount/withdrawNorate',
            routerUrl: '/opccount/withdrawNorate',
            treeNodeList: [],
          },
          {
            moduleId: 797,
            moduleNameCn: '首页',
            moduleNameEn: 'Home',
            moduleParentId: 796,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/opccount',
            routerUrl: '/opccount',
            treeNodeList: [],
          },
        ],
      },
    ],
  },
  {
    moduleNameCn: '信息中心',
    moduleNameEn: 'INFORMATION CENTER',
    moduleId: 1,
    nodes: [
      {
        moduleId: 606,
        moduleNameCn: '交易查询',
        moduleNameEn: 'Transaction',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 607,
            moduleNameCn: '正式交易',
            moduleNameEn: 'General Transaction',
            moduleParentId: 606,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/officialTrade',
          },
          {
            moduleId: 608,
            moduleNameCn: '挡掉交易',
            moduleNameEn: 'Blocked Transaction',
            moduleParentId: 606,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/blockTransactions',
          },
          {
            moduleId: 609,
            moduleNameCn: '未付款交易',
            moduleNameEn: 'Unpaid Transaction',
            moduleParentId: 606,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/unpaid',
          },
          {
            moduleId: 752,
            moduleNameCn: '预授权交易',
            moduleNameEn: 'Pre-auth Transaction',
            moduleParentId: 606,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/pre-authorization',
          },
          {
            moduleId: 753,
            moduleNameCn: 'MOTO交易',
            moduleNameEn: 'MOTO Query',
            moduleParentId: 606,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/motoTransaction',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-jiaoyichachaxun',
      },
      {
        moduleId: 719,
        moduleNameCn: '财务专区',
        moduleNameEn: 'Funding Reports',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 720,
            moduleNameCn: '账户资金',
            moduleNameEn: 'Account Funds',
            moduleParentId: 719,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/accountFunds',
          },
          {
            moduleId: 721,
            moduleNameCn: '交易明细',
            moduleNameEn: 'Trans Details',
            moduleParentId: 719,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/accountCapitalTransactionDetails',
          },
          {
            moduleId: 722,
            moduleNameCn: '交易划款',
            moduleNameEn: 'Trans Settlement',
            moduleParentId: 719,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/queryTradeSett',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-caiwuzhuanqu',
      },
      {
        moduleId: 791,
        moduleNameCn: '银行结算模式',
        moduleNameEn: 'Bank Settlement Model',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 792,
            moduleNameCn: '交易明细',
            moduleNameEn: 'Transaction Details',
            moduleParentId: 791,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/transactionDetails',
          },
          {
            moduleId: 793,
            moduleNameCn: '对账单',
            moduleNameEn: 'Statement',
            moduleParentId: 791,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/statement',
          },
          {
            moduleId: 794,
            moduleNameCn: '月账单',
            moduleNameEn: 'Monthly Billing',
            moduleParentId: 791,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/monthlyBilling',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-bank-settlement-model',
      },
      {
        moduleId: 757,
        moduleNameCn: '海关上送',
        moduleNameEn: 'Customs Upload',
        moduleParentId: 0,
        nodes: [],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-haiguanshangsong',
        moduleUrl: '/orderQuery',
      },
      {
        moduleId: 825,
        moduleNameCn: '消息通知',
        moduleNameEn: 'Notification Center',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 826,
            moduleNameCn: '系统公告',
            moduleNameEn: 'General Notice',
            moduleParentId: 825,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/messageList',
          },
          {
            moduleId: 827,
            moduleNameCn: '拒付通知',
            moduleNameEn: 'Chargeback Notice',
            moduleParentId: 825,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/chargebackNotice',
          },
          {
            moduleId: 828,
            moduleNameCn: '伪冒通知',
            moduleNameEn: 'Fraud Notice',
            moduleParentId: 825,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/fraudNotice',
          },
          {
            moduleId: 829,
            moduleNameCn: '调单通知',
            moduleNameEn: 'Retrieval Notice',
            moduleParentId: 825,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/retrievalNotice',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-xiaoxizhongxin',
      },
    ],
    treeNodeList: [
      {
        moduleId: 606,
        moduleNameCn: '交易查询',
        moduleNameEn: 'Transaction',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 607,
            moduleNameCn: '正式交易',
            moduleNameEn: 'General Transaction',
            moduleParentId: 606,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/officialTrade',
          },
          {
            moduleId: 608,
            moduleNameCn: '挡掉交易',
            moduleNameEn: 'Blocked Transaction',
            moduleParentId: 606,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/blockTransactions',
          },
          {
            moduleId: 609,
            moduleNameCn: '未付款交易',
            moduleNameEn: 'Unpaid Transaction',
            moduleParentId: 606,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/unpaid',
          },
          {
            moduleId: 752,
            moduleNameCn: '预授权交易',
            moduleNameEn: 'Pre-auth Transaction',
            moduleParentId: 606,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/pre-authorization',
          },
          {
            moduleId: 753,
            moduleNameCn: 'MOTO交易',
            moduleNameEn: 'MOTO Query',
            moduleParentId: 606,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/motoTransaction',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-jiaoyichachaxun',
        moduleIconName: 'icon-jiaoyichachaxun',
        routerUrl: '/officialTrade',
        treeNodeList: [
          {
            moduleId: 607,
            moduleNameCn: '正式交易',
            moduleNameEn: 'General Transaction',
            moduleParentId: 606,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/officialTrade',
            routerUrl: '/officialTrade',
            treeNodeList: [],
          },
          {
            moduleId: 608,
            moduleNameCn: '挡掉交易',
            moduleNameEn: 'Blocked Transaction',
            moduleParentId: 606,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/blockTransactions',
            routerUrl: '/blockTransactions',
            treeNodeList: [],
          },
          {
            moduleId: 609,
            moduleNameCn: '未付款交易',
            moduleNameEn: 'Unpaid Transaction',
            moduleParentId: 606,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/unpaid',
            routerUrl: '/unpaid',
            treeNodeList: [],
          },
          {
            moduleId: 752,
            moduleNameCn: '预授权交易',
            moduleNameEn: 'Pre-auth Transaction',
            moduleParentId: 606,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/pre-authorization',
            routerUrl: '/pre-authorization',
            treeNodeList: [],
          },
          {
            moduleId: 753,
            moduleNameCn: 'MOTO交易',
            moduleNameEn: 'MOTO Query',
            moduleParentId: 606,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/motoTransaction',
            routerUrl: '/motoTransaction',
            treeNodeList: [],
          },
        ],
      },
      {
        moduleId: 719,
        moduleNameCn: '财务专区',
        moduleNameEn: 'Funding Reports',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 720,
            moduleNameCn: '账户资金',
            moduleNameEn: 'Account Funds',
            moduleParentId: 719,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/accountFunds',
          },
          {
            moduleId: 721,
            moduleNameCn: '交易明细',
            moduleNameEn: 'Trans Details',
            moduleParentId: 719,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/accountCapitalTransactionDetails',
          },
          {
            moduleId: 722,
            moduleNameCn: '交易划款',
            moduleNameEn: 'Trans Settlement',
            moduleParentId: 719,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/queryTradeSett',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-caiwuzhuanqu',
        moduleIconName: 'icon-caiwuzhuanqu',
        routerUrl: '/accountFunds',
        treeNodeList: [
          {
            moduleId: 720,
            moduleNameCn: '账户资金',
            moduleNameEn: 'Account Funds',
            moduleParentId: 719,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/accountFunds',
            routerUrl: '/accountFunds',
            treeNodeList: [],
          },
          {
            moduleId: 721,
            moduleNameCn: '交易明细',
            moduleNameEn: 'Trans Details',
            moduleParentId: 719,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/accountCapitalTransactionDetails',
            routerUrl: '/accountCapitalTransactionDetails',
            treeNodeList: [],
          },
          {
            moduleId: 722,
            moduleNameCn: '交易划款',
            moduleNameEn: 'Trans Settlement',
            moduleParentId: 719,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/queryTradeSett',
            routerUrl: '/queryTradeSett',
            treeNodeList: [],
          },
        ],
      },
      {
        moduleId: 791,
        moduleNameCn: '银行结算模式',
        moduleNameEn: 'Bank Settlement Model',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 792,
            moduleNameCn: '交易明细',
            moduleNameEn: 'Transaction Details',
            moduleParentId: 791,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/transactionDetails',
          },
          {
            moduleId: 793,
            moduleNameCn: '对账单',
            moduleNameEn: 'Statement',
            moduleParentId: 791,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/statement',
          },
          {
            moduleId: 794,
            moduleNameCn: '月账单',
            moduleNameEn: 'Monthly Billing',
            moduleParentId: 791,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/monthlyBilling',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-bank-settlement-model',
        moduleIconName: 'icon-bank-settlement-model',
        routerUrl: '/transactionDetails',
        treeNodeList: [
          {
            moduleId: 792,
            moduleNameCn: '交易明细',
            moduleNameEn: 'Transaction Details',
            moduleParentId: 791,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/transactionDetails',
            routerUrl: '/transactionDetails',
            treeNodeList: [],
          },
          {
            moduleId: 793,
            moduleNameCn: '对账单',
            moduleNameEn: 'Statement',
            moduleParentId: 791,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/statement',
            routerUrl: '/statement',
            treeNodeList: [],
          },
          {
            moduleId: 794,
            moduleNameCn: '月账单',
            moduleNameEn: 'Monthly Billing',
            moduleParentId: 791,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/monthlyBilling',
            routerUrl: '/monthlyBilling',
            treeNodeList: [],
          },
        ],
      },
      {
        moduleId: 757,
        moduleNameCn: '海关上送',
        moduleNameEn: 'Customs Upload',
        moduleParentId: 0,
        nodes: [],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-haiguanshangsong',
        moduleUrl: '/orderQuery',
        moduleIconName: 'icon-haiguanshangsong',
        routerUrl: '/orderQuery',
        treeNodeList: [],
      },
      {
        moduleId: 825,
        moduleNameCn: '消息通知',
        moduleNameEn: 'Notification Center',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 826,
            moduleNameCn: '系统公告',
            moduleNameEn: 'General Notice',
            moduleParentId: 825,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/messageList',
          },
          {
            moduleId: 827,
            moduleNameCn: '拒付通知',
            moduleNameEn: 'Chargeback Notice',
            moduleParentId: 825,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/chargebackNotice',
          },
          {
            moduleId: 828,
            moduleNameCn: '伪冒通知',
            moduleNameEn: 'Fraud Notice',
            moduleParentId: 825,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/fraudNotice',
          },
          {
            moduleId: 829,
            moduleNameCn: '调单通知',
            moduleNameEn: 'Retrieval Notice',
            moduleParentId: 825,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/retrievalNotice',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-xiaoxizhongxin',
        moduleIconName: 'icon-xiaoxizhongxin',
        routerUrl: '/messageList',
        treeNodeList: [
          {
            moduleId: 826,
            moduleNameCn: '系统公告',
            moduleNameEn: 'General Notice',
            moduleParentId: 825,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/messageList',
            routerUrl: '/messageList',
            treeNodeList: [],
          },
          {
            moduleId: 827,
            moduleNameCn: '拒付通知',
            moduleNameEn: 'Chargeback Notice',
            moduleParentId: 825,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/chargebackNotice',
            routerUrl: '/chargebackNotice',
            treeNodeList: [],
          },
          {
            moduleId: 828,
            moduleNameCn: '伪冒通知',
            moduleNameEn: 'Fraud Notice',
            moduleParentId: 825,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/fraudNotice',
            routerUrl: '/fraudNotice',
            treeNodeList: [],
          },
          {
            moduleId: 829,
            moduleNameCn: '调单通知',
            moduleNameEn: 'Retrieval Notice',
            moduleParentId: 825,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/retrievalNotice',
            routerUrl: '/retrievalNotice',
            treeNodeList: [],
          },
        ],
      },
    ],
  },
  {
    moduleNameCn: '管理中心',
    moduleNameEn: 'ADMINISTRATION CENTER',
    moduleId: 2,
    nodes: [
      {
        moduleId: 771,
        moduleNameCn: '风控管理',
        moduleNameEn: 'Risk Management',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 822,
            moduleNameCn: '黑名单管理',
            moduleNameEn: 'Blacklist Management',
            moduleParentId: 771,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/blackListManagement',
          },
          {
            moduleId: 821,
            moduleNameCn: '白名单管理',
            moduleNameEn: 'Whitelist Management',
            moduleParentId: 771,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/whiteListManagement',
          },
          {
            moduleId: 772,
            moduleNameCn: '高欺诈风险警报通知',
            moduleNameEn: 'High Fraud Risk Alert Notification',
            moduleParentId: 771,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/highRiskOfFraudAlert',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-highRiskOfFraudAlert',
      },
      {
        moduleId: 738,
        moduleNameCn: '数据分析',
        moduleNameEn: 'Business Analytics',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 601,
            moduleNameCn: '可视化图表',
            moduleNameEn: 'Visual Analytics',
            moduleParentId: 738,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/home',
          },
          {
            moduleId: 735,
            moduleNameCn: '数据分析报表',
            moduleNameEn: 'Data Analysis Report',
            moduleParentId: 738,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/dataDownloadReport',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-keshihuabaobiao',
      },
      {
        moduleId: 611,
        moduleNameCn: '异常交易管理',
        moduleNameEn: 'All Exceptions',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 820,
            moduleNameCn: '争议交易',
            moduleNameEn: 'Dispute',
            moduleParentId: 611,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/disputeTransactions',
          },
          {
            moduleId: 615,
            moduleNameCn: '拒付交易',
            moduleNameEn: 'Chargeback',
            moduleParentId: 611,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/repudiateTransactions',
          },
          {
            moduleId: 614,
            moduleNameCn: '调单交易',
            moduleNameEn: 'Retrieval',
            moduleParentId: 611,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/retrievalTransactions',
          },
          {
            moduleId: 613,
            moduleNameCn: '伪冒交易',
            moduleNameEn: 'Fraud',
            moduleParentId: 611,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/phishingTrading',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-yichangjiaoyiguanli',
      },
      {
        moduleId: 697,
        moduleNameCn: '报表管理',
        moduleNameEn: 'Report Management',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 807,
            moduleNameCn: 'CX交易报表菜单',
            moduleNameEn: 'CXTrade report',
            moduleParentId: 697,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/report/queryCxTradeReport',
          },
          {
            moduleId: 698,
            moduleNameCn: '交易月报',
            moduleNameEn: 'Transaction Report',
            moduleParentId: 697,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/transactionReport',
          },
          {
            moduleId: 808,
            moduleNameCn: 'CX结算报表菜单',
            moduleNameEn: 'CXSettlement report',
            moduleParentId: 697,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/report/queryCxSettlementReport',
          },
          {
            moduleId: 836,
            moduleNameCn: '小程序运营支持',
            moduleNameEn: 'wx SupportInfo',
            moduleParentId: 697,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/monthlySettlementReport',
          },
          {
            moduleId: 699,
            moduleNameCn: '结算月报',
            moduleNameEn: 'Monthly Report',
            moduleParentId: 697,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/monthlySettlementReport',
          },
          {
            moduleId: 764,
            moduleNameCn: '资金日报',
            moduleNameEn: 'Daily Report',
            moduleParentId: 697,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/dailyReport',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-baobiaoguanli',
      },
      {
        moduleId: 684,
        moduleNameCn: 'LINK管理',
        moduleNameEn: 'Pay By LINK',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 685,
            moduleNameCn: 'LINK创建',
            moduleNameEn: 'LINK Create',
            moduleParentId: 684,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/linkCreate',
          },
          {
            moduleId: 686,
            moduleNameCn: 'LINK查询',
            moduleNameEn: 'LINK Management',
            moduleParentId: 684,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/linkQuery',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-linkguanli',
      },
      {
        moduleId: 804,
        moduleNameCn: '日志管理',
        moduleNameEn: 'Log Management',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 805,
            moduleNameCn: '登录日志',
            moduleNameEn: 'Login Log',
            moduleParentId: 804,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/log/getLoginLogList',
          },
          {
            moduleId: 806,
            moduleNameCn: '操作日志',
            moduleNameEn: 'Operation Log',
            moduleParentId: 804,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/log/getOperateLogList',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-log',
      },
      {
        moduleId: 758,
        moduleNameCn: '退款管理',
        moduleNameEn: 'Refund',
        moduleParentId: 0,
        nodes: [],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-tuikuanguanli',
        moduleUrl: '/refundmentQuery',
      },
      {
        moduleId: 814,
        moduleNameCn: '开发者',
        moduleNameEn: 'Developer',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 815,
            moduleNameCn: '终端设置',
            moduleNameEn: 'Terminals Setting',
            moduleParentId: 814,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/gateway/list',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-developer',
      },
      {
        moduleId: 812,
        moduleNameCn: '邮箱管理',
        moduleNameEn: 'Email Management',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 813,
            moduleNameCn: '收件人管理',
            moduleNameEn: 'Addressee Management',
            moduleParentId: 812,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/emailManagement',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'Frame71',
      },
      {
        moduleId: 759,
        moduleNameCn: '网站管理',
        moduleNameEn: 'Terminal Management',
        moduleParentId: 0,
        nodes: [],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-zhongduanguanli',
        moduleUrl: '/websiteManagement',
      },
      {
        moduleId: 760,
        moduleNameCn: '下载专区',
        moduleNameEn: 'Fashion Download',
        moduleParentId: 0,
        nodes: [],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-icon-xiazaizhuanqu',
        moduleUrl: '/downloadTask',
      },
      {
        moduleId: 681,
        moduleNameCn: '帮助中心',
        moduleNameEn: 'FAQ',
        moduleParentId: 0,
        nodes: [],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-wenhao',
        moduleUrl:
          'https://support.oceanpayment.com,https://support.oceanpayment.com/en',
      },
    ],
    treeNodeList: [
      {
        moduleId: 771,
        moduleNameCn: '风控管理',
        moduleNameEn: 'Risk Management',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 822,
            moduleNameCn: '黑名单管理',
            moduleNameEn: 'Blacklist Management',
            moduleParentId: 771,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/blackListManagement',
          },
          {
            moduleId: 821,
            moduleNameCn: '白名单管理',
            moduleNameEn: 'Whitelist Management',
            moduleParentId: 771,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/whiteListManagement',
          },
          {
            moduleId: 772,
            moduleNameCn: '高欺诈风险警报通知',
            moduleNameEn: 'High Fraud Risk Alert Notification',
            moduleParentId: 771,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/highRiskOfFraudAlert',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-highRiskOfFraudAlert',
        moduleIconName: 'icon-highRiskOfFraudAlert',
        routerUrl: '/blackListManagement',
        treeNodeList: [
          {
            moduleId: 822,
            moduleNameCn: '黑名单管理',
            moduleNameEn: 'Blacklist Management',
            moduleParentId: 771,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/blackListManagement',
            routerUrl: '/blackListManagement',
            treeNodeList: [],
          },
          {
            moduleId: 821,
            moduleNameCn: '白名单管理',
            moduleNameEn: 'Whitelist Management',
            moduleParentId: 771,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/whiteListManagement',
            routerUrl: '/whiteListManagement',
            treeNodeList: [],
          },
          {
            moduleId: 772,
            moduleNameCn: '高欺诈风险警报通知',
            moduleNameEn: 'High Fraud Risk Alert Notification',
            moduleParentId: 771,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/highRiskOfFraudAlert',
            routerUrl: '/highRiskOfFraudAlert',
            treeNodeList: [],
          },
        ],
      },
      {
        moduleId: 738,
        moduleNameCn: '数据分析',
        moduleNameEn: 'Business Analytics',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 601,
            moduleNameCn: '可视化图表',
            moduleNameEn: 'Visual Analytics',
            moduleParentId: 738,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/home',
          },
          {
            moduleId: 735,
            moduleNameCn: '数据分析报表',
            moduleNameEn: 'Data Analysis Report',
            moduleParentId: 738,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/dataDownloadReport',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-keshihuabaobiao',
        moduleIconName: 'icon-keshihuabaobiao',
        routerUrl: '/home',
        treeNodeList: [
          {
            moduleId: 601,
            moduleNameCn: '可视化图表',
            moduleNameEn: 'Visual Analytics',
            moduleParentId: 738,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/home',
            routerUrl: '/home',
            treeNodeList: [],
          },
          {
            moduleId: 735,
            moduleNameCn: '数据分析报表',
            moduleNameEn: 'Data Analysis Report',
            moduleParentId: 738,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/dataDownloadReport',
            routerUrl: '/dataDownloadReport',
            treeNodeList: [],
          },
        ],
      },
      {
        moduleId: 611,
        moduleNameCn: '异常交易管理',
        moduleNameEn: 'All Exceptions',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 820,
            moduleNameCn: '争议交易',
            moduleNameEn: 'Dispute',
            moduleParentId: 611,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/disputeTransactions',
          },
          {
            moduleId: 615,
            moduleNameCn: '拒付交易',
            moduleNameEn: 'Chargeback',
            moduleParentId: 611,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/repudiateTransactions',
          },
          {
            moduleId: 614,
            moduleNameCn: '调单交易',
            moduleNameEn: 'Retrieval',
            moduleParentId: 611,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/retrievalTransactions',
          },
          {
            moduleId: 613,
            moduleNameCn: '伪冒交易',
            moduleNameEn: 'Fraud',
            moduleParentId: 611,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/phishingTrading',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-yichangjiaoyiguanli',
        moduleIconName: 'icon-yichangjiaoyiguanli',
        routerUrl: '/disputeTransactions',
        treeNodeList: [
          {
            moduleId: 820,
            moduleNameCn: '争议交易',
            moduleNameEn: 'Dispute',
            moduleParentId: 611,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/disputeTransactions',
            routerUrl: '/disputeTransactions',
            treeNodeList: [],
          },
          {
            moduleId: 615,
            moduleNameCn: '拒付交易',
            moduleNameEn: 'Chargeback',
            moduleParentId: 611,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/repudiateTransactions',
            routerUrl: '/repudiateTransactions',
            treeNodeList: [],
          },
          {
            moduleId: 614,
            moduleNameCn: '调单交易',
            moduleNameEn: 'Retrieval',
            moduleParentId: 611,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/retrievalTransactions',
            routerUrl: '/retrievalTransactions',
            treeNodeList: [],
          },
          {
            moduleId: 613,
            moduleNameCn: '伪冒交易',
            moduleNameEn: 'Fraud',
            moduleParentId: 611,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/phishingTrading',
            routerUrl: '/phishingTrading',
            treeNodeList: [],
          },
        ],
      },
      {
        moduleId: 697,
        moduleNameCn: '报表管理',
        moduleNameEn: 'Report Management',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 807,
            moduleNameCn: 'CX交易报表菜单',
            moduleNameEn: 'CXTrade report',
            moduleParentId: 697,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/report/queryCxTradeReport',
          },
          {
            moduleId: 698,
            moduleNameCn: '交易月报',
            moduleNameEn: 'Transaction Report',
            moduleParentId: 697,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/transactionReport',
          },
          {
            moduleId: 808,
            moduleNameCn: 'CX结算报表菜单',
            moduleNameEn: 'CXSettlement report',
            moduleParentId: 697,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/report/queryCxSettlementReport',
          },
          {
            moduleId: 836,
            moduleNameCn: '小程序运营支持',
            moduleNameEn: 'wx SupportInfo',
            moduleParentId: 697,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/monthlySettlementReport',
          },
          {
            moduleId: 699,
            moduleNameCn: '结算月报',
            moduleNameEn: 'Monthly Report',
            moduleParentId: 697,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/monthlySettlementReport',
          },
          {
            moduleId: 764,
            moduleNameCn: '资金日报',
            moduleNameEn: 'Daily Report',
            moduleParentId: 697,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/dailyReport',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-baobiaoguanli',
        moduleIconName: 'icon-baobiaoguanli',
        routerUrl: '/report/queryCxTradeReport',
        treeNodeList: [
          {
            moduleId: 807,
            moduleNameCn: 'CX交易报表菜单',
            moduleNameEn: 'CXTrade report',
            moduleParentId: 697,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/report/queryCxTradeReport',
            routerUrl: '/report/queryCxTradeReport',
            treeNodeList: [],
          },
          {
            moduleId: 698,
            moduleNameCn: '交易月报',
            moduleNameEn: 'Transaction Report',
            moduleParentId: 697,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/transactionReport',
            routerUrl: '/transactionReport',
            treeNodeList: [],
          },
          {
            moduleId: 808,
            moduleNameCn: 'CX结算报表菜单',
            moduleNameEn: 'CXSettlement report',
            moduleParentId: 697,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/report/queryCxSettlementReport',
            routerUrl: '/report/queryCxSettlementReport',
            treeNodeList: [],
          },
          {
            moduleId: 836,
            moduleNameCn: '小程序运营支持',
            moduleNameEn: 'wx SupportInfo',
            moduleParentId: 697,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/monthlySettlementReport',
            routerUrl: '/monthlySettlementReport',
            treeNodeList: [],
          },
          {
            moduleId: 699,
            moduleNameCn: '结算月报',
            moduleNameEn: 'Monthly Report',
            moduleParentId: 697,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/monthlySettlementReport',
            routerUrl: '/monthlySettlementReport',
            treeNodeList: [],
          },
          {
            moduleId: 764,
            moduleNameCn: '资金日报',
            moduleNameEn: 'Daily Report',
            moduleParentId: 697,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/dailyReport',
            routerUrl: '/dailyReport',
            treeNodeList: [],
          },
        ],
      },
      {
        moduleId: 684,
        moduleNameCn: 'LINK管理',
        moduleNameEn: 'Pay By LINK',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 685,
            moduleNameCn: 'LINK创建',
            moduleNameEn: 'LINK Create',
            moduleParentId: 684,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/linkCreate',
          },
          {
            moduleId: 686,
            moduleNameCn: 'LINK查询',
            moduleNameEn: 'LINK Management',
            moduleParentId: 684,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/linkQuery',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-linkguanli',
        moduleIconName: 'icon-linkguanli',
        routerUrl: '/linkCreate',
        treeNodeList: [
          {
            moduleId: 685,
            moduleNameCn: 'LINK创建',
            moduleNameEn: 'LINK Create',
            moduleParentId: 684,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/linkCreate',
            routerUrl: '/linkCreate',
            treeNodeList: [],
          },
          {
            moduleId: 686,
            moduleNameCn: 'LINK查询',
            moduleNameEn: 'LINK Management',
            moduleParentId: 684,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/linkQuery',
            routerUrl: '/linkQuery',
            treeNodeList: [],
          },
        ],
      },
      {
        moduleId: 804,
        moduleNameCn: '日志管理',
        moduleNameEn: 'Log Management',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 805,
            moduleNameCn: '登录日志',
            moduleNameEn: 'Login Log',
            moduleParentId: 804,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/log/getLoginLogList',
          },
          {
            moduleId: 806,
            moduleNameCn: '操作日志',
            moduleNameEn: 'Operation Log',
            moduleParentId: 804,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/log/getOperateLogList',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-log',
        moduleIconName: 'icon-log',
        routerUrl: '/log/getLoginLogList',
        treeNodeList: [
          {
            moduleId: 805,
            moduleNameCn: '登录日志',
            moduleNameEn: 'Login Log',
            moduleParentId: 804,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/log/getLoginLogList',
            routerUrl: '/log/getLoginLogList',
            treeNodeList: [],
          },
          {
            moduleId: 806,
            moduleNameCn: '操作日志',
            moduleNameEn: 'Operation Log',
            moduleParentId: 804,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/log/getOperateLogList',
            routerUrl: '/log/getOperateLogList',
            treeNodeList: [],
          },
        ],
      },
      {
        moduleId: 758,
        moduleNameCn: '退款管理',
        moduleNameEn: 'Refund',
        moduleParentId: 0,
        nodes: [],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-tuikuanguanli',
        moduleUrl: '/refundmentQuery',
        moduleIconName: 'icon-tuikuanguanli',
        routerUrl: '/refundmentQuery',
        treeNodeList: [],
      },
      {
        moduleId: 814,
        moduleNameCn: '开发者',
        moduleNameEn: 'Developer',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 815,
            moduleNameCn: '终端设置',
            moduleNameEn: 'Terminals Setting',
            moduleParentId: 814,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/gateway/list',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-developer',
        moduleIconName: 'icon-developer',
        routerUrl: '/gateway/list',
        treeNodeList: [
          {
            moduleId: 815,
            moduleNameCn: '终端设置',
            moduleNameEn: 'Terminals Setting',
            moduleParentId: 814,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/gateway/list',
            routerUrl: '/gateway/list',
            treeNodeList: [],
          },
        ],
      },
      {
        moduleId: 812,
        moduleNameCn: '邮箱管理',
        moduleNameEn: 'Email Management',
        moduleParentId: 0,
        nodes: [
          {
            moduleId: 813,
            moduleNameCn: '收件人管理',
            moduleNameEn: 'Addressee Management',
            moduleParentId: 812,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/emailManagement',
          },
        ],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'Frame71',
        moduleIconName: 'Frame71',
        routerUrl: '/emailManagement',
        treeNodeList: [
          {
            moduleId: 813,
            moduleNameCn: '收件人管理',
            moduleNameEn: 'Addressee Management',
            moduleParentId: 812,
            nodes: [],
            moduleType: 1,
            modelLocation: 0,
            moduleUrl: '/emailManagement',
            routerUrl: '/emailManagement',
            treeNodeList: [],
          },
        ],
      },
      {
        moduleId: 759,
        moduleNameCn: '网站管理',
        moduleNameEn: 'Terminal Management',
        moduleParentId: 0,
        nodes: [],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-zhongduanguanli',
        moduleUrl: '/websiteManagement',
        moduleIconName: 'icon-zhongduanguanli',
        routerUrl: '/websiteManagement',
        treeNodeList: [],
      },
      {
        moduleId: 760,
        moduleNameCn: '下载专区',
        moduleNameEn: 'Fashion Download',
        moduleParentId: 0,
        nodes: [],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-icon-xiazaizhuanqu',
        moduleUrl: '/downloadTask',
        moduleIconName: 'icon-icon-xiazaizhuanqu',
        routerUrl: '/downloadTask',
        treeNodeList: [],
      },
      {
        moduleId: 681,
        moduleNameCn: '帮助中心',
        moduleNameEn: 'FAQ',
        moduleParentId: 0,
        nodes: [],
        moduleType: 1,
        modelLocation: 0,
        moduleIcon: 'icon-wenhao',
        moduleUrl:
          'https://support.oceanpayment.com,https://support.oceanpayment.com/en',
        moduleIconName: 'icon-wenhao',
        routerUrl:
          'https://support.oceanpayment.com,https://support.oceanpayment.com/en',
        treeNodeList: [],
      },
    ],
  },
]);
/** computed */

/** watch */

/** life cycle function */

/** methods */
</script>

<style lang="less" scoped></style>
